### PR TITLE
2025 Remove navigation controller from SL

### PR DESCRIPTION
**Pull request by zamorastp**

### CODE REVIEW

**Comment by zamorastp** [comment]
I was not able to reproduce this bug yesterday, but I believe this change should fix the problem. We had an additional navigation controller to show the privacy policy. I removed it and use SFSafariViewController instead

**Comment by clausjoergensen** [comment]
👀

**Comment by clausjoergensen** [comment]
Looks better now, but could we improve on the transition so the semi-transparent overlay is added _before_ the "animate in from bottom" animation is done? (see gif)

Simulator Screen Recording - iPhone 12 (14 4) - 2022-02-02 at 11 44 58

Simulator Screen Shot - iPhone 12 (14 4) - 2022-02-02 at 11 44 37

**Comment by zamorastp** [comment]
> Looks better now, but could we improve on the transition so the semi-transparent overlay is added _before_ the "animate in from bottom" animation is done? (see gif)
> 
> It looks weird seeing the semi-transparent overlay animate in like some "box" on top of the UI ;)
> 
> Simulator Screen Recording - iPhone 12 (14 4) - 2022-02-02 at 11 44 58

Yeap, i have ticket for it (todo in current sprint) ;) 
Screenshot 2022-02-02 at 11 50 23

**Review by clausjoergensen — APPROVED** [review]

**Pull request merged**
